### PR TITLE
feat: use python3 and env file

### PR DESCRIPTION
**Pull request by juev**
* python2 is not working anymore, we should use python3
* move configuration parameters to env file
* create `.env-example` file
* info to README file
* store backups in one directory
* specify SLEEP and ARGS from env
* update alpine version

### CODE REVIEW

**Comment by umputun** [comment]
This PR not just changing  python version (btw, "python2 is not working anymore" is not the case for the container) which maybe ok, as long as the change is transparent.

However, I see no reason to make things more complicated by introducing .env and I don't want the change the basic logic, making daily directories and keeping a limited number of days around

**Comment by juev** [comment]
My fail, I opened this request when I have done only fix python version. :(

I can revert all other changes, if needed.

**Comment by umputun** [comment]
i have no problem with the image update and py3, as long as it continue to work and fully compatible with the existing version

**Comment by juev** [comment]
I created #4 PR.

**Pull request closed without merging**
