### PR TITLE
Fix issue with MAX_BACKUPS

### PR DESCRIPTION
**Pull request by igorkamyshev**
Hello!

I know, it very rough solution, but it works for my case (issue #1). Can you review this PR and give me your feedback? Why this solution are bad?

### CODE REVIEW

**Comment by umputun** [comment]
My problem with this solution - it solves the problem I don't understand and can't reproduce

**Comment by igorkamyshev** [comment]
Yes, I understand. Can you check this solution? Maybe, it is okay, and can works fine for your cases and for my unreproduceable case.

**Comment by umputun** [comment]
ok, I have found a justification for such a change. The current find-based solution based on 1d wait period as it treats `MAX_BACKUPS` as a number of days to keep. In some cases, it may lead to +1 backup left and, if sleep 1d changed to something else, it won't be the max number of backups anymore.

Following your idea I'd suggest some simplification:

`ls -d1r /srv/var/* | tail -n +${MAX_BACKUPS} | xargs rm -rf`

I have tested this one-liner quicky and it seems to be legit. Pls check it out and confirm if it works in your enviroment as well.

**Comment by igorkamyshev** [comment]
I guess, you forgot about slash. But, in general this line works fine:

`ls -d1r /srv/var/*/ | tail -n +${MAX_BACKUPS} | xargs rm -rf`

**Comment by umputun** [comment]
works fine for me without /. As far as I can see the only difference is what argument rm will get, and `rm -rf /foo/bar` seems to remove ` /foo/bar` just fine. So, unless I miss something I see no reason for this `/`

**Comment by igorkamyshev** [comment]
Sorry, it was premature outcome. I run some tests and found other problem. If I have 3 dirs in `srv/var` and MAX_BACKUPS sets to 2, it command remove 2 dirs, but must remove only one.

It isn't fatal problem, I can just set MAX_BACKUPS to larger value. 🤗

**Comment by umputun** [comment]
> It isn't fatal problem, I can just set MAX_BACKUPS to a larger value. 

Well, this is inconsistent, confusing, and I'm considering it to be a major problem. Maybe the solution is to "flip" it and do the head, like this: `ls -d1 /srv/var/* | head -n -${MAX_BACKUPS} | xargs rm -rf`. My quick test showed we don't have +1 issue this way.

**Comment by igorkamyshev** [comment]
I have error on local machine: `head: illegal line count -- -3`. Can't try in container now, but looks like correct code.

**Comment by umputun** [comment]
works from container:

```
> ls -d1r /srv/var/*
/srv/var/20190730-050532
/srv/var/20190729-044605
/srv/var/20190728-042807
/srv/var/20190727-041007
/srv/var/20190726-035135
/srv/var/20190725-033201
/srv/var/20190724-031306
/srv/var/20190723-025410
/srv/var/20190722-125912
```

```
> ls -d1 /srv/var/* | head -n -5 | xargs echo
/srv/var/20190722-125912 /srv/var/20190723-025410 /srv/var/20190724-031306 /srv/var/20190725-033201
```

**Comment by igorkamyshev** [comment]
Great! It is very good news for me. Can you release version with this fix?

**Comment by igorkamyshev** [comment]
I just updated this PR, if merge is more comfortable for you (please, squash commits, I did really many commits without clear approach).

**Comment by igorkamyshev** [comment]
Thanks a lot. Also, thanks for the podcast, it is really great! 🙏

**Pull request merged**
